version: '3'

services:
  bank:
    image: bank_app:latest
    restart: always
    environment:
      POSTGRES_URI: postgres://demo:demo@postgresql/bank?sslmode=disable
    ports:
      - "8000:8000"
  postgresql:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: bank
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo
    ports:
      - "5432:5432"
